# Generated by Django 6.0.4 on 2026-05-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='driverID',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurantID',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
