# Generated by Django 6.0.4 on 2026-04-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promoID', models.AutoField(primary_key=True, serialize=False)),
                ('promoCode', models.CharField(max_length=20, unique=True)),
                ('discountPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online Payment')], max_length=20)),
                ('paymentDate', models.DateTimeField(auto_now_add=True)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('transactionReference', models.CharField(max_length=100, unique=True)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('promoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refundID', models.AutoField(primary_key=True, serialize=False)),
                ('refundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refundDate', models.DateTimeField(auto_now_add=True)),
                ('refundStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], max_length=20)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment')),
            ],
        ),
    ]
